[package]
name = "project_euler"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
Inflector = { version = "0.11.4", default-features = false }

[[bench]]
name = "problem_004_bench"
harness = false

[[bench]]
name = "problem_007_bench"
harness = false

[[bench]]
name = "problem_008_bench"
harness = false

[[bench]]
name = "problem_009_bench"
harness = false

[[bench]]
name = "problem_010_bench"
harness = false

[[bench]]
name = "problem_011_bench"
harness = false

[[bench]]
name = "problem_012_bench"
harness = false

[lints]
clippy.pedantic = { level = "warn", priority = -1 }
clippy.nursery = { level = "warn", priority = -1 }
clippy.redundant_else = "allow"
